(node:24547) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_RESET at https://faok.com
    at navigate (/home/mfsgvg/website-evidence-collector/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/mfsgvg/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/mfsgvg/website-evidence-collector/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/mfsgvg/website-evidence-collector/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/mfsgvg/website-evidence-collector/website-evidence-collector.js:167:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
